### ISSUE TITLE
go mod missing 

### ISSUE THREAD

**Issue by shubham-cmyk** [douglasmakey/ursho#8]
![Screenshot from 2022-09-18 00-26-09](https://user-images.githubusercontent.com/69793468/190872395-8b70acfe-a2f0-4c00-85b9-6a1df4b893fa.png)

**Comment by douglasmakey** [comment]
Sorry, I don't know why I never got the GitHub notification!

https://github.com/douglasmakey/ursho/commit/4a6666093b9a3fd6bdb40d845076d1c719a24203

**Comment by shubham-cmyk** [comment]
Finally it's done!! :smile:
